config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'
  
  resources :tickets

  resources :technologies

  resources :engineers

  resources :applications

  resources :statuses

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
    respond_to do |format|
      format.html
      format.csv 
      format.xls
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status=Status.find(params[:id])
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      #params[:status]
      params.require(:status).permit(:name)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper

	def get_status_tickets_count status
		status.tickets.count
	end
	def get_status_technologies_count status
		status.tickets.count
	end
	def get_status_applications_count status 
		sum=0
		status.tickets.each do |ticket|
			sum+=Application.where(id:ticket.application_id).distinct.count
		end
		return sum
	end
	def get_status_engineers_count status
		sum=0
		status.tickets.each do |ticket|
			sum+=Engineer.where(id:ticket.engineer_id).distinct.count
		end
		return sum
	end
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%= render 'welcome/menu'%>
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<%= render 'welcome/menu'%>

<p id="notice"><%= notice %></p>

<p>
  Download:

  <%= link_to "Excel", statuses_path(format: "xls") %>
</p>

<h1>Listing Statuses</h1>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Status</th>
      <th>Tickets</th>
      <th>Technologies</th>
      <th>Applications</th>
      <th>Engineers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= get_status_tickets_count(status) %></td>
        <td><%= get_status_technologies_count(status) %></td>
        <td><%= get_status_applications_count(status) %></td>
        <td><%= get_status_engineers_count(status) %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
        <Cell><Data ss:Type="String">Ticket</Data></Cell>
        <Cell><Data ss:Type="String">Technology</Data></Cell>
        <Cell><Data ss:Type="String">Applications</Data></Cell>
        <Cell><Data ss:Type="String">Engineers</Data></Cell>
      </Row>
    <% @statuses.each do |status| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= status.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= status.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_status_tickets_count(status) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_status_technologies_count(status) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_status_applications_count(status) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_status_engineers_count(status) %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/statuses/new.html.erb
<%= render 'welcome/menu'%>
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>
<%= @status.name %>
<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

<h1>Listing Tickets</h1>

<table border="1" align='center'>
  <thead>
    <tr>
      <th>Incident</th>
      <th>Last update sent on</th>
      <th>Engineer</th>
      <th>Application</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status.tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.incident %> </td>
        <td><%= ticket.dou %> </td>
        <td><%= get_engineer_name(ticket.engineer_id)%></td>
        <td><%= get_application_name(ticket.application_id)%></td>
        <td><%= get_status_name(ticket.status_id)%></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>