config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'
  
  resources :tickets

  resources :technologies

  resources :engineers

  resources :applications

  resources :statuses

end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :technology
	has_many :tickets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  include ApplicationHelper
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
    @statuses=Status.all.sort_by(&:name)
    respond_to do |format|
      format.html
      format.csv 
      format.xls
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
    @technologies=Technology.all.sort_by(&:name)
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :technology_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_technology_name id
     Technology.find(id).name
  end 

  def get_engineer_name id
      Engineer.find(id).name
  end
  def get_application_name id
      Application.find(id).name
  end
    def get_status_name id
      Status.find(id).name
  end
  def get_tickets_count
      Ticket.all.count
  end
    def get_engineers_count
      Engineer.all.count
  end
    def get_applications_count
      Application.all.count
  end
    def get_statuses_count
      Status.all.count
  end
    def get_technologies_count
      Technology.all.count
  end

        
end

app/helpers/applications_helper.rb
module ApplicationsHelper
	def get_application_tickets_count application
       application.tickets.count
    end

    def get_application_status_tickets_count status, application
        Ticket.where(status_id:status.id,application_id:application.id).count
    end
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  </div>
  <div class="field">
      <%= f.label :technology %><br />
      <%= f.collection_select :technology_id, @technologies, :id, :name, include_blank: false %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<%= render 'welcome/menu'%>
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>

<p>
  Download:

  <%= link_to "Excel", applications_path(format: "xls") %>
</p>

<h1>Listing Applications</h1>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Application</th>
      <th>Technology</th>
      <th>Tickets</th>
      <% @statuses.each do |status| %>
         <th><%= status.name%></th>
      <% end %>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= get_technology_name(application.technology_id)%></td>
         <td><%= get_application_tickets_count(application) %></td>
      <% @statuses.each do |status| %>
         <td><%= get_application_status_tickets_count(status,application) %></td>
      <% end %>        
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Application</Data></Cell>
        <Cell><Data ss:Type="String">Technology</Data></Cell>
        <Cell><Data ss:Type="String">Tickets</Data></Cell>
       <% @statuses.each do |status| %>
         <Cell><Data ss:Type="String"><%= status.name%></Data></Cell>
       <% end %>
      </Row>
    <% @applications.each do |application| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= application.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= application.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_technology_name(application.technology_id) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_application_tickets_count(application) %></Data></Cell>
        <% @statuses.each do |status| %>
        <Cell><Data ss:Type="String"><%= get_application_status_tickets_count(status,application) %> </Data></Cell>
        <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/applications/new.html.erb
<%= render 'welcome/menu'%>
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>
<%= @application.name %><br>
<%= get_technology_name(@application.technology_id) %>
<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>



<h1>Listing Tickets</h1>

<table border="1" align='center'>
  <thead>
    <tr>
      <th>Incident</th>
      <th>Last update sent on</th>
      <th>Engineer</th>
      <th>Application</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application.tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.incident %> </td>
        <td><%= ticket.dou %> </td>
        <td><%= get_engineer_name(ticket.engineer_id)%></td>
        <td><%= get_application_name(ticket.application_id)%></td>
        <td><%= get_status_name(ticket.status_id)%></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>