config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'
  
  resources :tickets

  resources :technologies

  resources :engineers

  resources :applications

  resources :statuses

end

app/models/engineer.rb
class Engineer < ActiveRecord::Base
	has_many :tickets, dependent: :destroy
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: [:show, :edit, :update, :destroy]

  # GET /engineers
  # GET /engineers.json
  def index
    @engineers = Engineer.all
    @statuses=Status.all.sort_by(&:name)
    respond_to do |format|
      format.html
      format.csv 
      format.xls
    end
  end

  # GET /engineers/1
  # GET /engineers/1.json
  def show
    @engineer=Engineer.find(params[:id])
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
  end

  # POST /engineers
  # POST /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)

    respond_to do |format|
      if @engineer.save
        format.html { redirect_to @engineer, notice: 'Engineer was successfully created.' }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1
  # PATCH/PUT /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to @engineer, notice: 'Engineer was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1
  # DELETE /engineers/1.json
  def destroy
    @engineer.destroy
    respond_to do |format|
      format.html { redirect_to engineers_url, notice: 'Engineer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer
      @engineer = Engineer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_params
      params.require(:engineer).permit(:name)
    end
end

app/helpers/engineers_helper.rb
module EngineersHelper

	def get_engineer_tickets_count engineer
		engineer.tickets.count
	end
    def get_engineer_status_tickets_count status, engineer
        Ticket.where(status_id:status.id,engineer_id:engineer.id).count
    end
end

app/views/engineers/_form.html.erb
<%= form_for(@engineer) do |f| %>
  <% if @engineer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engineer.errors.count, "error") %> prohibited this engineer from being saved:</h2>

      <ul>
      <% @engineer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :fmno %><br />
      <%= f.text_field :fmno %>
  </div>
  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engineers/edit.html.erb
<%= render 'welcome/menu'%>
<h1>Editing Engineer</h1>

<%= render 'form' %>

<%= link_to 'Show', @engineer %> |
<%= link_to 'Back', engineers_path %>

app/views/engineers/index.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>

<p>
  Download:

  <%= link_to "Excel", engineers_path(format: "xls") %>
</p>

<h1>Listing Engineers</h1>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Engineer</th>
      <th>Tickets</th>
      <% @statuses.each do |status| %>
         <th><%= status.name%></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engineers.each do |engineer| %>
      <tr>
        <td><%= engineer.name %></td>
        <td><%= get_engineer_tickets_count(engineer) %></td>
      <% @statuses.each do |status| %>
         <td><%= get_engineer_status_tickets_count(status,engineer) %></td>
      <% end %>
        <td><%= link_to 'Show', engineer %></td>
        <td><%= link_to 'Edit', edit_engineer_path(engineer) %></td>
        <td><%= link_to 'Destroy', engineer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engineer', new_engineer_path %>

app/views/engineers/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Engineer</Data></Cell>
        <Cell><Data ss:Type="String">Tickets</Data></Cell>
       <% @statuses.each do |status| %>
         <Cell><Data ss:Type="String"><%= status.name%></Data></Cell>
       <% end %>
      </Row>
    <% @engineers.each do |engineer| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= engineer.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= engineer.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_engineer_tickets_count(engineer) %></Data></Cell>
        <% @statuses.each do |status| %>
        <Cell><Data ss:Type="String"><%= get_engineer_status_tickets_count(status,engineer) %> </Data></Cell>
        <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/engineers/new.html.erb
<%= render 'welcome/menu'%>
<h1>New Engineer</h1>

<%= render 'form' %>

<%= link_to 'Back', engineers_path %>

app/views/engineers/show.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>
<%= @engineer.name %>
<%= link_to 'Edit', edit_engineer_path(@engineer) %> |
<%= link_to 'Back', engineers_path %>


<h1>Listing Tickets</h1>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Incident</th>
      <th>Last update sent on</th>
      <th>Engineer</th>
      <th>Application</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engineer.tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.incident %> </td>
        <td><%= ticket.dou %> </td>
        <td><%= get_engineer_name(ticket.engineer_id)%></td>
        <td><%= get_application_name(ticket.application_id)%></td>
        <td><%= get_status_name(ticket.status_id)%></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>