config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'
  
  resources :tickets

  resources :technologies

  resources :engineers

  resources :applications

  resources :statuses

end

app/models/technology.rb
class Technology < ActiveRecord::Base
	 has_many :applications, dependent: :destroy
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.paginate(:page => params[:page], :per_page => 10)
    @statuses=Status.all.sort_by(&:name)
    respond_to do |format|
      format.html
      format.csv 
      format.xls
    end
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
    @technology=Technology.find(params[:id])
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper

	def get_technology_applications_count technology
         technology.applications.count
    end
    def get_technology_tickets_count technology
    	sum=0
    	technology.applications.each do |application|
    		sum+=application.tickets.count
    	end
    	return sum
    end
    def get_technology_status_tickets_count status,technology
    	sum=0
     	technology.applications.each do |application|
    		sum+=Ticket.where(status_id:status.id,application_id:application.id).count
    	end 
    	return sum  
    end	
end

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
  <% if @technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% @technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<%= render 'welcome/menu'%>
<h1>Editing Technology</h1>

<%= render 'form' %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<%= render 'welcome/menu'%>

<p id="notice"><%= notice %></p>

<p>
  Download:

  <%= link_to "Excel", technologies_path(format: "xls") %>
</p>

<h1>Listing Technologies</h1>
<%= will_paginate @technologies %>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Technology</th>
      <th>Applications</th>
      <th>Tickets</th>
      <% @statuses.each do |status| %>
         <th><%= status.name%></th>
      <% end %>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name %></td>
        <td><%= get_technology_applications_count(technology) %></td>
        <td><%= get_technology_tickets_count(technology) %></td>
      <% @statuses.each do |status| %>
         <td><%= get_technology_status_tickets_count(status,technology) %></td>
      <% end %>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Technology</Data></Cell>
        <Cell><Data ss:Type="String">Applications</Data></Cell>
       <% @statuses.each do |status| %>
         <Cell><Data ss:Type="String"><%= status.name%></Data></Cell>
       <% end %>
      </Row>
    <% @technologies.each do |technology| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= technology.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= technology.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_technology_applications_count(technology) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= get_technology_tickets_count(technology) %></Data></Cell>
        <% @statuses.each do |status| %>
        <Cell><Data ss:Type="String"><%= get_technology_status_tickets_count(status,technology) %> </Data></Cell>
        <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/technologies/new.html.erb
<%= render 'welcome/menu'%>
<h1>New Technology</h1>

<%= render 'form' %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<%= render 'welcome/menu'%>
<p id="notice"><%= notice %></p>

<table border="1" align="center">
  <thead>
    <tr>
      <th>Technology</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
	<td><%= @technology.name %></td>
	<td><%= link_to 'Edit', edit_technology_path(@technology) %> |</td>
	<td><%= link_to 'Back', technologies_path %></td>
  </tbody>
</table>


<h1>Listing Tickets</h1>

<table border="1" align='center'>
  <thead>
    <tr>
      <th>Incident</th>
      <th>Last update sent on</th>
      <th>Engineer</th>
      <th>Application</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% @technology.applications.each do |application|%>
     <% application.tickets.each do |ticket| %>
       <tr>
         <td><%= ticket.incident %> </td>
         <td><%= ticket.dou %> </td>
         <td><%= get_engineer_name(ticket.engineer_id)%></td>
         <td><%= get_application_name(ticket.application_id)%></td>
         <td><%= get_status_name(ticket.status_id)%></td>
         <td><%= link_to 'Show', ticket %></td>
         <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
         <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>